<?php

/**
 * Implements hook_form_alter()
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function vih_subscription_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //dpm($form);
}

function vih_subscription_theme() {
  return [
    'vih_subscription_long_course_order_form' => array(
      'render element' => 'form',
    ),
    'vih_subscription_class_selection_radios' => array(
      'render element' => 'radios',
    ),
    'vih_subscription_short_course_order_form' => array(
      'render element' => 'form',
    ),
    'vih_subscription_thank_you_page' => array(
      'render element' => 'page',
    )
  ];
}

?>