<?php

/**
 * Implements hook_form_alter()
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function vih_subscription_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_vih_course_period_form') {
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = 'vih_subscription_course_period_form_submit';
      }
    }
  }
}

function vih_subscription_course_period_form_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $new_course_link = \Drupal::l(t('new course'), \Drupal\Core\Url::fromRoute('node.add', array('node_type' => 'vih_long_cource')));
  $new_course_period_link = \Drupal::l(t('new course period'), \Drupal\Core\Url::fromRoute('node.add', array('node_type' => 'vih_course_period')));
  drupal_set_message(t('Would you like to create a @course_link or @course_period_link now?', array(
    '@course_link' => $new_course_link,
    '@course_period_link' => $new_course_period_link
  )));

  $form_state->setRedirect('system.admin_content');
}

function vih_subscription_theme() {
  return [
    'vih_subscription_long_course_order_form' => array(
      'render element' => 'form',
    ),
    'vih_subscription_class_selection_radios' => array(
      'render element' => 'radios',
    ),
    'vih_subscription_short_course_order_form' => array(
      'render element' => 'form',
    ),
    'vih_subscription_event_order_form' => array(
      'render element' => 'form',
    ),
    'vih_subscription_confirmation_page' => array(
      'render element' => 'page',
    ),
    'vih_subscription_thank_you_page' => array(
      'render element' => 'page',
    ),
    'vih_subscription_cancelled_page' => array(
      'render element' => 'page',
    ),
    'vih_subscription_error_page' => array(
      'render element' => 'page',
    )
  ];
}


?>