<?php

/**
 * @file
 * Contains vih_domain_detect.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function vih_domain_detect_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the vih_domain_detect module.
    case 'help.page.vih_domain_detect':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds a CSS class to the html for CSS to detect the domain.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_page().
 */
function vih_domain_detect_preprocess_html(&$variables) {
  if (strpos($_SERVER['SERVER_NAME'], 'vies') !== false) {
    $variables['attributes']['class'][] = 'is-vies';
  } else {
    $variables['attributes']['class'][] = 'is-vih';
  }
}
