<?php
/**
 * @file
 * Datetime tweak module.
 * 
 * Remove seconds from datetime widget
 */

/**
 * Implements hook_element_info_alter().
 */
function datetime_tweaks_element_info_alter(array &$types) {
  $types['datetime']['#process'][] = '_datetime_tweaks_datetime_set_format';
}

function _datetime_tweaks_datetime_set_format($element) {

  // Remove seconds in browsers that support HTML5 type=date.
  $element['time']['#attributes']['step'] = 60;
  return $element;
}
